### ISSUE TITLE
Update FontAwesome to version 5

### ISSUE THREAD

**Issue by aeksco** [codotype/codotype-vuejs-vuex-bootstrap-generator#11]
Currently using FontAwesome 4.7 served over CDN - it should be updated to version 5.x

All usage of FontAwesome in the generated code, as well as the `model_options` in `meta.js`, will need to be updated.

**Comment by ldevernay** [comment]
Just submitted a pull request on this, upgraded to FontAwesome 5.3.1.

**Comment by aeksco** [comment]
Resolved by #15
